development:
  adapter: postgresql
  encoding: unicode
  database: myflix_development
  pool: 5
  username: vincent
  password: xc1946sjc

test:
  adapter: postgresql
  encoding: unicode
  database: myflix_test
  pool: 5
  username: vincent
  password: xc1946sjc
